app/cart/urls.py
from cart.views import CartAddView,CartInfoView,CarUpdateView,CartDeleteView
from django.urls import path,re_path
app_name = 'cart'
urlpatterns = [
    path('',CartInfoView.as_view(),name='show'),  #购物车页面显示
    path('add',CartAddView.as_view(),name='add'),  #购物车记录添加
    path('update',CarUpdateView.as_view(),name='update'),  #购物车记录更新
    path('delete',CartDeleteView.as_view(),name='delete'),  #购物车商品删除
]

app/goods/urls.py
from django.urls import path,re_path
from goods.views import IndexView,DetailView,ListView
app_name = 'goods'
urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    re_path(r'^goods/(?P<goods_id>\d+)$',DetailView.as_view(),name='detail'),
    re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',ListView.as_view(),name='list')

]

app/user/urls.py
from user.views import RegisterView,ActiveView,LoginView,UserInfoView,UserOrderView,UserAddressView,LogoutView
from django.urls import path,re_path
from django.contrib.auth.decorators import login_required

app_name='user'
urlpatterns = [
    path('register/',RegisterView.as_view(),name='register'),   #用户注册
    path('login/',LoginView.as_view(),name='login'),    #用户登录
    path('logout/',LogoutView.as_view(),name='logout'),    #注销登录
    re_path('active/(?P<token>.*)$',ActiveView.as_view(),name='active'),    #用户激活
    path('',UserInfoView.as_view(),name='user'),    #用户信息
    path('order/',UserOrderView.as_view(),name='order'),    #用户订单
    path('address/',UserAddressView.as_view(),name='address'),   #用户地址

]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/',include('tinymce.urls')),   #富文本编辑器
    path('search/',include('haystack.urls')),   #全文检索框架
    path('user/', include('user.urls',namespace='user')),
    path('cart/', include('cart.urls',namespace='cart')),
    path('order/', include('order.urls',namespace='order')),
    path('', include('goods.urls',namespace='goods')),

]

app/cart/models.py
from django.db import models

# Create your models here.

app/cart/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.views.generic import View
from goods.models import GoodsSKU
from django.http import JsonResponse
from django_redis import get_redis_connection
# Create your views here.
class CartAddView(View):
    '''购物车记录添加'''
    def post(self,request):
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return JsonResponse({'res':0,'errmsg':'未登录，不能添加'})
        #接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        #数据校验
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整！'})
        #校验添加的商品数量
        try:
            count=int(count)
        except Exception as e:
            return JsonResponse({'res':2,'errmsg':'商品数目出错'})
        #校验商品是否存在
        try:
            goods = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({'res':3,'errmsg':'商品不存在！'})
        #业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        #尝试获取sku_id的值->hget cart_key属性
        #如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key,sku_id)
        if cart_count:
            #累加购物车中的数量
            count+=int(cart_count)
        #校验商品的库存

        if count > goods.stock:
            return JsonResponse({'res':4,'errmsg':'商品库存不足！'})
        #设置hash中sku_id对应的值
        #hset->如果sku_id已经存在，更新数据，如果sku_id不存在，添加数据
        conn.hset(cart_key,sku_id,count)
        #计算用户购物车中商品的条目数
        total_count = conn.hlen(cart_key)
        #返回应答
        return JsonResponse({'res':5,'total_count':total_count,'message':'添加成功！'})

class CartInfoView(View):
    '''显示购物车信息'''
    def get(self,request):
        #获取当前登录的用户
        user = request.user
        #获取redis连接
        conn = get_redis_connection('default')
        #获取购物车信息
        cart_key = 'cart_%d'%user.id
        #skus是一个字典{'商品id':'数量'}
        cart_dict = conn.hgetall(cart_key)
        skus=[]

        total_count = 0   #商品总数
        total_price = 0   #商品总价
        #遍历skus
        for sku_id,count in cart_dict.items():
            #根据商品ID查出商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            #动态给商品添加属性‘数量’count
            sku.count = int(count)
            #动态给商品添加属性‘小计’amount
            sku.amount = int(count)*sku.price
            #将商品添加到列表中
            skus.append(sku)

            total_count+=int(count)
            total_price+=int(count)*sku.price
            #上下文信息
            context = {
                'skus':skus,
                'total_count':total_count,
                'total_price':total_price
            }
        #给页面返回值
        return render(request,'cart.html',context)

class CarUpdateView(View):
    '''购物车记录更新'''
    def post(self,request):
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return JsonResponse({'res':0,'errmsg':'未登录，不能更新'})
        #接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        #数据校验
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整！'})
        #校验添加的商品数量
        try:
            count=int(count)
        except Exception as e:
            return JsonResponse({'res':2,'errmsg':'商品数目出错'})
        #校验商品是否存在
        try:
            goods = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({'res':3,'errmsg':'商品不存在！'})
        #业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        #校验商品的库存

        if count > goods.stock:
            return JsonResponse({'res':4,'errmsg':'商品库存不足！'})
        #设置hash中sku_id对应的值
        #hset->如果sku_id已经存在，更新数据，如果sku_id不存在，添加数据
        conn.hset(cart_key,sku_id,count)
        #获取购物车商品的数量
        total_count=0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count+=int(val)

        #返回应答
        return JsonResponse({'res':5,'total_count':total_count,'message':'添加成功！'})


class CartDeleteView(View):
    '''删除购物车商品'''
    def post(self,request):
        #获取要删除的商品的id
        sku_id = request.POST.get('sku_id')
        #获取用户
        user = request.user

        #判断用户是否登录
        if not user.is_authenticated:
            return JsonResponse({'res':1,'errmsg':'用户未登录,不能删除商品'})

        #判断商品id是否合法
        if not sku_id:
            return JsonResponse({'res':2,'errmsg':'无效的商品id'})

        #判断商品是否存在
        try:
            goods=GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':3,'errmsg':'商品不存在！'})

        #业务处理
        #获取redis连接
        conn = get_redis_connection('default')

        cart_key = 'cart_%d'%user.id
        conn.hdel(cart_key,sku_id)
        #计算购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count+=int(val)

        return JsonResponse({'res':'4','message':'删除成功','total_count':total_count})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{# 网页标题 #}
    <title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    {# 网页顶部引入文件 #}
    {% block topfiles %}{% endblock %}
</head>
<body>
    {# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
            {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
				</div>
            {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
            {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static "images/logo.png" %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
			    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网站主体内容块 #}
{% block body %}{% endblock body %}


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	{# 网页底部html元素块 #}
    {% block bottom %}{% endblock %}
    {# 网页底部引入文件块 #}
    {% block bottomfiles %}

    {% endblock %}
</body>
</html>

templates/base_detail_list.html
{# 商品详情页,列表页模板 #}
{% extends "base.html" %}

{% block body %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>
				<ul class="subnav">
                {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1%}" class="{{type.logo}}">{{type.name}}</a></li>
                {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url "goods:index" %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
{# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{# 用户中心模板 #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% load staticfiles %}

    {% block sub_page_name %}|&nbsp;&nbsp;&nbsp;&nbsp;用户中心{% endblock sub_page_name %}

{% block body %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}"{% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}"{% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            {% block right_content %}{% endblock right_content %}
        </div>

    </div>
{% endblock body %}

templates/detail.html
{# 商品详情页 #}
{% extends "base_detail_list.html" %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% load staticfiles %}
{% block main_content %}
    <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' sku.type.id 1%}">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>
	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{sku.image.url}}"></div>

		<div class="goods_detail_list fr">
			<h3>{{sku.name}}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{sku.price}}</em></span>
				<span class="show_unit">单  位：{{sku.unite}}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1" onblur="input_calc_count()">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
            <div>
                <p>其它规格：</p>
                <Ul>
                    {% for sku in same_spu_skus %}
                        <li><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></li>
                    {% endfor %}

                </Ul>
            </div>
			<div class="total">总价：<em>元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
                {% csrf_token %}
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="#">{% url 'goods:detail' sku.id%}</a>{{ sku.name }}</h4>
                            <div class="prize">￥{{sku.price}}</div>
                        </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }}</dd>
				</dl>
			</div>
            <div class="tab_content">
                <dl>
                    {% for order in sku_orders %}

                        <dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;用户名：{{ order.order.user.username }}</dt>
                        <dd>评论内容：{{ order.comment }}</dd>
                    {% endfor %}
                </dl>
            </div>
		</div>
	</div>

	<div class="add_jump"></div>
{% endblock main_content %}

{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">

        //计算商品总价格
        function calc_goods_amount () {
            //获取商品数量和价格
            var price = $('.show_pirze').children('em').text();
            var count = $('.num_show').val();
            //计算
            var count = parseInt(count);
            var price = parseFloat(price);

            var amount = count*price
            //设置总价格
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }
        calc_goods_amount ()

        //增加商品数量
        $('.add').click(function () {
            //获得文本框里的数字
            var count = $('.num_show').val();
            var count = parseInt(count);
            //设置值
            var count = count+1
            $('.num_show').val(count);
            calc_goods_amount ()
        })
        //减少商品数量
        $('.minus').click(function () {
            //获得文本框里的数字
            var count = $('.num_show').val();
            var count = parseInt(count);
            //设置值
            var count = count-1
            if (count <= 0){
                $('.num_show').val(1);
            }else {
                $('.num_show').val(count);
                calc_goods_amount ()
            }

        })

        //输入商品数量计算价格
        function input_calc_count() {
            //获取商品数量和价格
            var price = $('.show_pirze').children('em').text();
            var count = $('.num_show').val();
            //判断输入值是否合法(只能为数字，不能为空，不能小于零)
            if (parseInt(count)<=0 || count.trim().length==0 || isNaN(count)){
                count = 1;
            }
            //重新设置商品数目
            var count = $('.num_show').val(count);
            //重新设置价格
            calc_goods_amount ()

        }
        //获取add_cart元素左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;
        //获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$('#add_cart').click(function() {
            //获取商品id和数量
            var sku_id = $('#add_cart').attr('sku_id');
            var sku_count = $('.num_show').val();

            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            //组织参数
            var params = {'sku_id': sku_id, 'count': sku_count, 'csrfmiddlewaretoken': csrf}
            //发起ajax_post请求，访问/cart/add，传递参数：sku_id count
            $.post('/cart/add', params, function (data) {
                if (data.res == 5) {
                    //添加成功
                    $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                //重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });

                        });
                } else {
                    //添加失败
                    alert(data.errmsg)
                }
            })
        })

	</script>
{% endblock bottomfiles %}

templates/index.html
{# 网站首页 #}
{% extends 'base.html' %}

    {% load staticfiles %}
	{% block title %}天天生鲜-首页{% endblock title %}
    {% block topfiles %}
        <script type="text/javascript" src="{% static "js/jquery-1.12.4.min.js" %}"></script>
	    <script type="text/javascript" src="{% static "js/jquery-ui.min.js" %}"></script>
	    <script type="text/javascript" src="{% static "js/slide.js" %}"></script>
    {% endblock topfiles %}


{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url "goods:index" %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
        {% for type in types %}
			<li><a href="{% url 'goods:list' type.id 1%}" class="{{type.logo}}">{{type.name}}</a></li>
        {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
            {% for banner in goods_banners %}
				<li><a href="#"><img src="{{banner.image.url}}" alt="幻灯片"></a></li>
            {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
        {% for banner in promotion_banners %}
			<a href="{{banner.url}}"><img src="{{ banner.image.url }}"></a>
		{% endfor %}
		</div>
	</div>
{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="{{forloop.counter}}">{{type.name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
            {% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
            {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1%}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
            {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{banner.sku.name}}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥{{banner.sku.price}}</div>
				</li>
            {% endfor %}
			</ul>
		</div>
	</div>
{% endfor %}

{% endblock body %}

templates/list.html
{# 商品列表页 #}
{% extends 'base_detail_list.html' %}

{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
    <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type.id 1%}">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %} class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %} class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %} class="active" {% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">

                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id skus_page.previous_page_number%}?sort={{ sort }}">上一页</a>
                {% endif %}

                {% for pindex in skus_page.paginator.page_range %}

                    {% if pindex == skus_page.number %}

                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}

                {% if skus_page.has_next %}
                    <a href="{% url 'goods:list' type.id skus_page.next_page_number%}?sort={{ sort }}">下一页</a>
                {% endif %}

			</div>
		</div>
	</div>
{% endblock main_content %}

templates/login.html
{# 登录页面 #}
{% extends 'base.html' %}
{% load  staticfiles %}

	{% block title %}天天生鲜-登录{% endblock title %}
    {% block topfiles %}
        <link rel="stylesheet" type="text/css" href="{%  static "css/reset.css" %}">
	    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    {% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}

{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static "images/logo02.png" %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
                     {# 不设置表单action时，提交表单时，会向浏览器地址栏中的地址提交数据 #}
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ username }}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" {{ checked }} name="remenber">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
                    {{ errmsg }}
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/user_center_info.html
{# 用户信息中心页面 #}
{% extends 'base_user_center.html' %}
{% load staticfiles %}


{% block right_content %}

    <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>

        <ul class="user_info_list">
            <li><span>用户名：</span>{{address.receiver}}</li>
        {% if address %}
            <li><span>联系方式：</span>{{address.phone}}</li>
            <li><span>联系地址：</span>{{address.addr}}</li>
        {% else %}
            <li><span>联系方式：</span>无默认</li>
            <li><span>联系地址：</span>无默认</li>
        {% endif %}
        </ul>


    </div>

    <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">
            {% for goods in goods_list %}
                <li>
                    <a href="{% url 'goods:detail' goods.id %}"><img src="{{goods.image.url}}"></a>
                    <h4><a href="detail.html">{{ goods.name }}</a></h4>
                    <div class="operate">
                        <span class="prize">￥{{goods.price}}</span>
                        <span class="unit">{{goods.price}}/{{goods.unite}}</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>
                {% empty %}
                无历史浏览记录
            {% endfor %}


        </ul>
    </div>
{% endblock right_content %}